Repository sagiegurari/cargo-make, pull requests merged in 2019-10, with the labels that each got.

#296 0.22.2
  CHANGELOG.md
  Cargo.toml
  Makefile.toml
  README.md
  docs/_includes/content.md
  examples/condition.toml
  examples/env.toml
  examples/script.sh
  examples/script.toml
  src/lib/Makefile.stable.toml
  src/lib/command.rs
  src/lib/command_test.rs
  src/lib/condition.rs
  src/lib/condition_test.rs
  src/lib/descriptor.rs
  src/lib/environment/mod.rs
  src/lib/environment/mod_test.rs
  src/lib/execution_plan.rs
  src/lib/execution_plan_test.rs
  src/lib/installer/mod.rs
  src/lib/io.rs
  src/lib/io_test.rs
  src/lib/mod.rs
  src/lib/runner_test.rs
  src/lib/scriptengine/mod.rs
  src/lib/scriptengine/mod_test.rs
  src/lib/scriptengine/os_script.rs
  src/lib/scriptengine/shell_to_batch.rs
  src/lib/test/test_files/text_file.txt
  src/lib/types.rs
  src/lib/types_test.rs
Labels: enhancement

#298 Add minimal example for drone.io
  docs/_includes/content.md
Labels: documentation

#299 Color configuration by environment variable
  docs/_includes/content.md
  examples/cargo-make/config.toml
  src/lib/cli.rs
  src/lib/cli_test.rs
  src/lib/logger.rs
  src/lib/logger_test.rs
  src/lib/types.rs
  src/lib/types_test.rs
Labels: enhancement

#303 0.23.0
  CHANGELOG.md
  README.md
  docs/_includes/content.md
  examples/cargo-make/config.toml
  src/lib/cli.rs
  src/lib/cli_test.rs
  src/lib/environment/mod.rs
  src/lib/environment/mod_test.rs
  src/lib/logger.rs
  src/lib/logger_test.rs
  src/lib/types.rs
  src/lib/types_test.rs
Labels: Breaking Change, enhancement
