Repository sagiegurari/cargo-make, pull requests merged in 2019-06, with the labels that each got.

#249 Update README - installing `cargo-make` when caching `cargo`
  docs/_includes/content.md
Labels: documentation

#250 0.19.5
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/_includes/content.md
  docs/_includes/nav.md
  examples/functions.toml
  examples/min_version.toml
  src/lib/Makefile.stable.toml
  src/lib/cli.rs
  src/lib/environment/mod.rs
  src/lib/profile.rs
  src/lib/profile_test.rs
  src/lib/types.rs
  src/lib/types_test.rs
  src/lib/version.rs
Labels: enhancement

#253 Allow passing an array of argument to test_arg
  docs/_includes/content.md
  src/lib/installer/crate_installer_test.rs
  src/lib/installer/mod_test.rs
  src/lib/installer/rustup_component_installer.rs
  src/lib/installer/rustup_component_installer_test.rs
  src/lib/types.rs
  src/lib/types_test.rs
Labels: enhancement

#256 0.21.0
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/_includes/content.md
  src/lib/installer/crate_installer_test.rs
  src/lib/installer/mod_test.rs
  src/lib/installer/rustup_component_installer.rs
  src/lib/installer/rustup_component_installer_test.rs
  src/lib/types.rs
  src/lib/types_test.rs
Labels: Breaking Change, enhancement
