Repository sagiegurari/cargo-make, pull requests merged in 2023-09, with the labels that each got.

#940 0.37.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/lib/descriptor/env.rs
  src/lib/runner.rs
Labels: bug, enhancement

#949 0.37.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/lib/environment/crateinfo.rs
  src/lib/environment/crateinfo_test.rs
  src/lib/environment/mod.rs
  src/lib/environment/mod_test.rs
Labels: bug, enhancement

#937 Add sub-command alternative to the readme
  docs/_includes/content.md
  docs/_includes/nav.md
Labels: documentation

#952 Enhancement: improve support for shebang script file extensions #926
  CHANGELOG.md
  src/lib/scriptengine/shebang_script.rs
  src/lib/scriptengine/shebang_script_test.rs
Labels: enhancement
